# Generated by Django 5.2 on 2025-05-25 01:08

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agenda', '0001_initial'),
        ('business', '0001_initial'),
        ('management', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('payment', models.CharField(choices=[('CASH', 'Dinheiro'), ('CREDIT', 'Cartão de Crédito'), ('DEBIT', 'Cartão de Débito'), ('PIX', 'Transferência PIX'), ('BOLETO', 'Boleto')], default='CASH', max_length=20)),
                ('status', models.CharField(choices=[('PENDING', 'Pendente'), ('COMPLETED', 'Completada'), ('CANCELED', 'Cancelada')], default='PENDING', max_length=20)),
                ('total_price', models.DecimalField(decimal_places=3, default=0, max_digits=15)),
                ('agenda_extra', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='agenda.agendaextra')),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='business.business')),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales', to='management.client')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_sales', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SaleItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('type', models.CharField(choices=[('PRODUCT', 'Product'), ('SERVICE', 'Service')], max_length=16)),
                ('quantity', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('snapshot_name', models.CharField(max_length=255)),
                ('snapshot_code', models.CharField(max_length=33)),
                ('snapshot_price', models.DecimalField(decimal_places=3, max_digits=15)),
                ('origin', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='management.offer')),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sale_items', to='sale.sale')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
