# Generated by Django 5.2 on 2025-05-22 16:11

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('business', '0014_alter_segment_options'),
        ('management', '0011_rename_duratiion_service_duration'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('payment', models.CharField(choices=[('CASH', 'Dinheiro'), ('CREDIT', 'Cartão de Crédito'), ('DEBIT', 'Cartão de Débito'), ('PIX', 'Transferência PIX'), ('BOLETO', 'Boleto')], default='CASH', max_length=20)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='business.business')),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales', to='management.client')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_sales', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SaleItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('PRODUCT', 'Product'), ('SERVICE', 'Service')], max_length=16)),
                ('quantity', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('snapshot_name', models.CharField(max_length=255)),
                ('snapshot_code', models.CharField(max_length=33)),
                ('snapshot_price', models.DecimalField(decimal_places=3, max_digits=15)),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sale.sale')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProductSaleItem',
            fields=[
                ('saleitem_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='sale.saleitem')),
                ('origin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='management.product')),
            ],
            options={
                'abstract': False,
            },
            bases=('sale.saleitem',),
        ),
        migrations.CreateModel(
            name='ServiceSaleItem',
            fields=[
                ('saleitem_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='sale.saleitem')),
                ('origin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='management.service')),
            ],
            options={
                'abstract': False,
            },
            bases=('sale.saleitem',),
        ),
    ]
