# Generated by Django 5.2 on 2025-06-03 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pendentes'), ('COMPLETED', 'Completadas'), ('CANCELED', 'Canceladas')], default='PENDING', max_length=20),
        ),
    ]
