# Generated by Django 5.2 on 2025-05-22 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pendente'), ('COMPLETED', 'Completada'), ('CANCELED', 'Cancelada')], default='PENDING', max_length=20),
        ),
    ]
