# Generated by Django 5.2 on 2025-05-24 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0003_sale_total_price_alter_saleitem_sale'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sale',
            options={'ordering': ['-created_at']},
        ),
    ]
