# Generated by Django 5.2 on 2025-05-24 19:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0007_agenda_created_by'),
        ('sale', '0004_alter_sale_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='agenda_extra',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='agenda.agendaextra'),
        ),
    ]
