# Generated by Django 5.2 on 2025-05-24 20:04

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0005_sale_agenda_extra'),
    ]

    operations = [
        migrations.AddField(
            model_name='saleitem',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='saleitem',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
