# Generated by Django 5.2 on 2025-05-08 15:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='segmentcategory',
            options={'ordering': ['code']},
        ),
        migrations.AlterField(
            model_name='segment',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='segments', to='business.segmentcategory'),
        ),
    ]
