# Generated by Django 5.2 on 2025-06-03 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='slug',
            field=models.CharField(blank=True, null=True, unique=True),
        ),
    ]
