# Generated by Django 5.2 on 2025-05-08 23:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0002_alter_segmentcategory_options_alter_segment_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='business',
            old_name='avatar',
            new_name='logo',
        ),
    ]
