# Generated by Django 5.2 on 2025-05-09 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0003_rename_avatar_business_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='color',
            field=models.CharField(blank=True, default='#FFFFFF', max_length=7),
        ),
    ]
