# Generated by Django 5.2 on 2025-05-13 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0004_business_color'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='segment',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='segmentcategory',
            options={'ordering': ['name']},
        ),
    ]
