# Generated by Django 5.2 on 2025-07-08 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0004_indicator_size'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='indicator',
            name='size',
        ),
        migrations.AddField(
            model_name='indicator',
            name='format',
            field=models.CharField(choices=[('INTEGER', 'Integer'), ('CURRENCY', 'Currency')], default='INTEGER', max_length=255),
        ),
    ]
