# Generated by Django 5.2 on 2025-05-15 16:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0005_alter_segment_options_alter_segmentcategory_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessconfig',
            name='agenda_end_time',
            field=models.TimeField(default=datetime.time(18, 0)),
        ),
        migrations.AddField(
            model_name='businessconfig',
            name='agenda_start_time',
            field=models.TimeField(default=datetime.time(7, 0)),
        ),
    ]
