# Generated by Django 5.2 on 2025-05-16 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0006_businessconfig_agenda_end_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessconfig',
            name='agenda_allow_conflicting_time',
            field=models.BooleanField(default=False),
        ),
    ]
