# Generated by Django 5.2 on 2025-05-22 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0007_businessconfig_agenda_allow_conflicting_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='business',
            name='segment',
        ),
    ]
