# Generated by Django 5.2 on 2025-05-22 07:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0008_remove_business_segment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Segment',
        ),
        migrations.DeleteModel(
            name='SegmentCategory',
        ),
    ]
