# Generated by Django 5.2 on 2025-05-22 07:20

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0009_delete_segment_delete_segmentcategory'),
    ]

    operations = [
        migrations.CreateModel(
            name='Segment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=24)),
                ('name', models.CharField(max_length=32)),
                ('description', models.CharField(max_length=255)),
                ('emoji', models.CharField(max_length=16)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
