# Generated by Django 5.2 on 2025-05-22 07:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0010_segment'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='segment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='business.segment'),
        ),
    ]
