# Generated by Django 5.2 on 2025-05-22 07:39

from django.db import migrations


def configure_default_segments(apps, schema_editor):
    Business = apps.get_model('business', 'Business')
    Segment = apps.get_model('business', 'Segment')
    default_segment = Segment.objects.filter(code=1).last()
    Business.objects.update(segment=default_segment)
    

class Migration(migrations.Migration):

    dependencies = [
        ('business', '0011_business_segment'),
    ]

    operations = [
        migrations.RunPython(configure_default_segments, migrations.RunPython.noop)
    ]
