# Generated by Django 5.2 on 2025-05-22 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0012_configure_default_segments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='segment',
            name='code',
            field=models.PositiveSmallIntegerField(max_length=24),
        ),
    ]
