# Generated by Django 5.2 on 2025-05-22 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0012_configure_default_segments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='segment',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='segment',
            name='updated_at',
        ),
    ]
