# Generated by Django 5.2 on 2025-05-22 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0013_alter_segment_code'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='segment',
            options={'ordering': ['code']},
        ),
    ]
