# Generated by Django 5.2 on 2025-05-22 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0014_alter_segment_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='segment',
            name='code',
            field=models.PositiveSmallIntegerField(),
        ),
    ]
