# Generated by Django 5.2 on 2025-05-08 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileupload',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='imageupload',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
