# Generated by Django 5.2 on 2025-06-03 23:05

import apps.upload.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileupload',
            name='file',
            field=models.FileField(upload_to=apps.upload.models.upload_to_using_model_uuid, validators=[apps.upload.models.validate_file_size, django.core.validators.FileExtensionValidator(['pdf', 'txt'])]),
        ),
        migrations.AlterField(
            model_name='imageupload',
            name='file',
            field=models.ImageField(upload_to=apps.upload.models.upload_to_using_model_uuid, validators=[apps.upload.models.validate_file_size, django.core.validators.FileExtensionValidator(['png', 'jpg', 'jpeg'])]),
        ),
    ]
