# Generated by Django 5.2 on 2025-05-10 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='address',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='client',
            name='cep',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
