# Generated by Django 5.2 on 2025-05-25 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='type',
            field=models.CharField(blank=True, choices=[('PRODUCT', 'Produto'), ('SERVICE', 'Serviço')], null=True),
        ),
    ]
