# Generated by Django 5.2 on 2025-07-08 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0002_offer_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='display_on_highlights',
            field=models.BooleanField(default=False),
        ),
    ]
