# Generated by Django 5.2 on 2025-05-10 01:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0002_client_address_client_cep'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='type',
        ),
        migrations.RemoveField(
            model_name='service',
            name='type',
        ),
    ]
