# Generated by Django 5.2 on 2025-05-10 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0003_remove_product_type_remove_service_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='color',
            field=models.CharField(blank=True, default='#FFFFFF', max_length=7),
        ),
    ]
