# Generated by Django 5.2 on 2025-05-10 05:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0004_client_color'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='current_cover',
            new_name='cover',
        ),
        migrations.RenameField(
            model_name='service',
            old_name='current_cover',
            new_name='cover',
        ),
    ]
