# Generated by Django 5.2 on 2025-05-10 19:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0006_alter_subcategory_category'),
        ('upload', '0002_alter_fileupload_name_alter_imageupload_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='cover',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='upload.imageupload'),
        ),
        migrations.AlterField(
            model_name='service',
            name='cover',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='upload.imageupload'),
        ),
    ]
