# Generated by Django 5.2 on 2025-05-10 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0007_alter_product_cover_alter_service_cover'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='duratiion',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
