# Generated by Django 5.2 on 2025-05-10 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0008_service_duratiion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='duratiion',
            field=models.PositiveSmallIntegerField(blank=True, default=30, null=True),
        ),
    ]
