# Generated by Django 5.2 on 2025-05-10 19:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0010_alter_service_duratiion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='service',
            old_name='duratiion',
            new_name='duration',
        ),
    ]
