# Generated by Django 5.2 on 2025-05-23 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0012_categorytemplate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='category',
        ),
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.DeleteModel(
            name='Subcategory',
        ),
    ]
