# Generated by Django 5.2 on 2025-05-23 23:08

import django.db.models.deletion
import uuid
from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('business', '0015_alter_segment_code'),
        ('management', '0015_category_business'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryBase',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('PRODUCT', 'Produto'), ('SERVICE', 'Serviço')], max_length=10)),
                ('name', models.CharField(max_length=255)),
                ('business', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='business.business')),
            ],
            options={
                'abstract': False,
            },
        ),
        
    ]
