# Generated by Django 5.2 on 2025-05-23 23:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0015_alter_segment_code'),
        ('management', '0016_categorybase'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryTemplateV2',
            fields=[
                ('categorybase_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='management.categorybase')),
                ('segment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='business.segment')),
            ],
            options={
                'abstract': False,
            },
            bases=('management.categorybase',),
        ),
    ]
