# Generated by Django 5.2 on 2025-05-23 23:19

from django.db import migrations


def migrate_data(apps, schema_editor):
    OldCategory = apps.get_model("management", "CategoryTemplate")
    NewTemplate = apps.get_model("management", "CategoryTemplateV2")
    for cat in OldCategory.objects.all():
        NewTemplate.objects.create(
            # id=cat.id,
            name=cat.name,
            type=cat.type,
            segment=cat.segment
        )

class Migration(migrations.Migration):

    dependencies = [
        ('management', '0017_categorytemplatev2'),
    ]

    operations = [
        migrations.RunPython(migrate_data, migrations.RunPython.noop)
    ]

    atomic = False