# Generated by Django 5.2 on 2025-05-23 23:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0018_migrate_categorytemplate_to_v2'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CategoryTemplate',
        ),
    ]
