# Generated by Django 5.2 on 2025-05-23 23:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0015_alter_segment_code'),
        ('management', '0019_delete_categorytemplate'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CategoryTemplateV2',
            new_name='CategoryTemplate',
        ),
    ]
