# Generated by Django 5.2 on 2025-05-20 17:41

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


def geneate_profile_preferences(apps, schema_editor):
    User = apps.get_model('account', 'User')
    UserPreference = apps.get_model('access', 'UserPreference')
    for user in User.objects.all():
        UserPreference.objects.create(user=user)

class Migration(migrations.Migration):

    dependencies = [
        ('access', '0002_initial'),
        ('upload', '0002_alter_fileupload_name_alter_imageupload_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPreference',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('color', models.CharField(blank=True, default='#FFFFFF', max_length=7)),
                ('avatar', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='upload.imageupload')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile_preference', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),

        migrations.RunPython(geneate_profile_preferences, reverse_code=migrations.RunPython.noop)
    ]
