services:
  # Web service (Backend: Django with Gunicorn)
  web:
    build:
      context: ./backend
      dockerfile: ./Dockerfile.backend 
    container_name: bittybiz_backend
    command: ./gunicorn.sh
    volumes:
      - static_volume:/app/staticfiles
    expose:
      - 8000
    networks:
      - postgres_shared_network

  frontend:
    build:
      context: ./frontend
      dockerfile: ./Dockerfile.frontend
    container_name: bittybiz_frontend
    volumes:
      - frontend_volume:/app
  
  nginx:
    image: nginx:alpine
    container_name: bittybiz_nginx
    depends_on:
      - web
      - frontend
    ports:
      - "80:80"
    volumes:
      - frontend_volume:/usr/share/nginx/html  # Serve frontend
      - static_volume:/app/staticfiles
      - ./nginx.conf:/etc/nginx/conf.d/default.conf  # Your custom config
    networks:
    - postgres_shared_network  

volumes:
  static_volume:
  frontend_volume:

networks:
  postgres_shared_network:
    external: true