# Generated by Django 5.2 on 2025-05-10 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agenda',
            name='observations',
            field=models.TextField(blank=True),
        ),
    ]
