# Generated by Django 5.2 on 2025-05-10 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0005_alter_agendaextra_agenda'),
    ]

    operations = [
        migrations.AddField(
            model_name='agendaextra',
            name='use_service_duration',
            field=models.BooleanField(default=False),
        ),
    ]
